# Basic set up for Actions and Docker. Security updates enabled via GitHub settings for other ecosystems.

version: 2
updates:

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
    # Add assignees
    assignees:
      - "zwass"

# Maintain dependencies for Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "fleetdm/go"
      - "fleetdm/infra"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
    # Add assignees
    assignees:
      - "fleetdm/go"
      - "fleetdm/infra"

# Maintain dependencies for website NPM
  - package-ecosystem: "npm"
    directory: "/website"
    labels:
      - "website"
    schedule:
      interval: "daily"
    # Disable version updates
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
    reviewers:
      - "eashaw"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
    assignees:
      - "eashaw"

# Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - lucasmrod
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
    # Add assignees
    assignees:
      - lucasmrod

# Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates
    open-pull-requests-limit: 0
    reviewers:
      - lukeheath
    allow:
      - dependency-type: "production"
    pull-request-branch-name:
      # Default is "/" which makes "docker tag" fail with
      # "not a valid repository/tag: invalid reference format".
      separator: "-"
    # Add assignees
    assignees:
      - lukeheath

  - package-ecosystem: npm
    directory: /ee/fleetd-chrome
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ee/tools/license
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infrastructure/loadtesting/terraform/docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infrastructure/sandbox/JITProvisioner/deprovisioner
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /infrastructure/sandbox/JITProvisioner/deprovisioner
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infrastructure/sandbox/JITProvisioner/lambda
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /infrastructure/sandbox/JITProvisioner/lambda
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infrastructure/sandbox/Monitoring/lambda
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /infrastructure/sandbox/Monitoring/lambda
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infrastructure/sandbox/PreProvisioner/lambda
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /infrastructure/sandbox/PreProvisioner/lambda
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /orbit/tools/ubuntu
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/bomutils-docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/fleet-docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/fleetctl-docker
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /tools/fleetctl-npm
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /tools/mdm/windows/poc-mdm-server
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/wix-docker
    schedule:
      interval: daily
